### get by id

GET http://localhost:8888/users/1

### login

POST http://localhost:8888/auth
Content-Type: application/json

{
  "email" : "test2@abv.bg",
  "password" : "tesS123!"
}

### register

POST http://localhost:8888/users
Content-Type: application/json

{
  "first_name" : "test",
  "last_name" : "test",
  "email" : "test4@abv.bg",
  "password" : "tesS123!",
  "confirm_password" : "tesS123!",
  "phone" : "123456789"
}

### register no phone

POST http://localhost:8888/users
Content-Type: application/json

{
  "first_name" : "test2",
  "last_name" : "test2",
  "email" : "test3@abv.bg",
  "password" : "tesT2123!",
  "confirm_password" : "tesT2123!"
}

### edit profile

PUT http://localhost:8888/users
Content-Type: application/json

{
  "first_name" : "test3",
  "last_name" : "test3",
  "phone" : "123456789"
}

### change password

PUT http://localhost:8888/users/pass
Content-Type: application/json

{
  "password" : "tesT123!",
  "new_password" : "Test1234!",
  "confirm_password" : "Test1234!"
}

### delete profile

DELETE http://localhost:8888/users
Content-Type: application/json

{
  "email" : "test3@abv.bg",
  "password" : "tesT2123!"
}

### log out
