### get by id - pizza

GET http://localhost:8888/menu/items/1

###get by id - drink

GET http://localhost:8888/menu/items/2

### get all ingredients for pizza

GET http://localhost:8888/menu/items/1/ingredients

### get all ingredients for drink -- like this?

GET http://localhost:8888/menu/items/2/ingredients

### get all items for category

GET http://localhost:8888/menu/categories/1

###
